version: '3.2'

services:
  ms_elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: "ms_elastic"
    restart: always
    hostname: "elastic"
    networks:
      - gateway
    environment:
      - "PS1=$$(whoami)@$$(hostname) $$ "
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9002:9002"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  ms_vnf_detector:
    container_name: "ms_vnf_detector"
    restart: always
    hostname: "vnf_detector"
    environment:
      - "PS1=$$(whoami)@$$(hostname) $$ "
    networks:
      - gateway
    image: vnf_detector_img
    build:
      context: vnf_detector/
      dockerfile: $PWD/vnf_detector/Dockerfile

volumes:
  es_data:

networks:
  gateway: {}